// Mocks generated by Mockito 5.4.6 from annotations
// in untitled1/test/data/repository/stock_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:untitled1/data/data_source/local_stock_data_source.dart' as _i2;
import 'package:untitled1/data/data_source/remote_stock_data_source.dart'
    as _i5;
import 'package:untitled1/data/model/stock_price.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LocalStockDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStockDataSource extends _i1.Mock
    implements _i2.LocalStockDataSource {
  MockLocalStockDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.StockPrice>> getStockPrices(String? ticker) =>
      (super.noSuchMethod(
            Invocation.method(#getStockPrices, [ticker]),
            returnValue: _i3.Future<List<_i4.StockPrice>>.value(
              <_i4.StockPrice>[],
            ),
          )
          as _i3.Future<List<_i4.StockPrice>>);

  @override
  void saveStockPrices(String? ticker, List<_i4.StockPrice>? prices) =>
      super.noSuchMethod(
        Invocation.method(#saveStockPrices, [ticker, prices]),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [RemoteStockDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteStockDataSource extends _i1.Mock
    implements _i5.RemoteStockDataSource {
  MockRemoteStockDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.StockPrice>> getStockPrices(String? ticker) =>
      (super.noSuchMethod(
            Invocation.method(#getStockPrices, [ticker]),
            returnValue: _i3.Future<List<_i4.StockPrice>>.value(
              <_i4.StockPrice>[],
            ),
          )
          as _i3.Future<List<_i4.StockPrice>>);
}
