// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7frlkU9qTdaUqApYaGZy4iF6TH94McWc',
    appId: '1:257157060609:web:a0e3e544f1c098c74c4800',
    messagingSenderId: '257157060609',
    projectId: 'fir-project-001-39393',
    authDomain: 'fir-project-001-39393.firebaseapp.com',
    storageBucket: 'fir-project-001-39393.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQyY0I4rvVLw4zlZd8k1jDH8RNgk5CQ04',
    appId: '1:257157060609:android:4bc8235903a473e34c4800',
    messagingSenderId: '257157060609',
    projectId: 'fir-project-001-39393',
    storageBucket: 'fir-project-001-39393.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdxfbiCe4ZGfuO2VClOzfPD0Dkpf-CeV8',
    appId: '1:257157060609:ios:f4a54fc9811503314c4800',
    messagingSenderId: '257157060609',
    projectId: 'fir-project-001-39393',
    storageBucket: 'fir-project-001-39393.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdxfbiCe4ZGfuO2VClOzfPD0Dkpf-CeV8',
    appId: '1:257157060609:ios:f4a54fc9811503314c4800',
    messagingSenderId: '257157060609',
    projectId: 'fir-project-001-39393',
    storageBucket: 'fir-project-001-39393.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7frlkU9qTdaUqApYaGZy4iF6TH94McWc',
    appId: '1:257157060609:web:cc6d160cf36d72334c4800',
    messagingSenderId: '257157060609',
    projectId: 'fir-project-001-39393',
    authDomain: 'fir-project-001-39393.firebaseapp.com',
    storageBucket: 'fir-project-001-39393.firebasestorage.app',
  );
}
